/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		AppointmentCard: typeof import(
			"./src/components/AppointmentCard.vue",
		)["default"]
		Appointments: typeof import("./src/components/Appointments.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		ScheduleCard: typeof import("./src/components/ScheduleCard.vue")["default"]
		Welcome: typeof import("./src/components/Welcome.vue")["default"]
	}
}
