/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCardSkeleton: typeof import('./src/components/bookings/AppointmentCardSkeleton.vue')['default']
    AssignmentLoadingState: typeof import('./src/components/booking/guest-assignment/AssignmentLoadingState.vue')['default']
    AssignmentProgressHeader: typeof import('./src/components/booking/guest-assignment/AssignmentProgressHeader.vue')['default']
    AssignmentSummarySidebar: typeof import('./src/components/booking/guest-assignment/AssignmentSummarySidebar.vue')['default']
    AssignmentValidationBanner: typeof import('./src/components/booking/guest-assignment/AssignmentValidationBanner.vue')['default']
    AvailableDatesList: typeof import('./src/components/booking/guest-assignment/AvailableDatesList.vue')['default']
    AvailableSlotsGrid: typeof import('./src/components/booking/guest-assignment/AvailableSlotsGrid.vue')['default']
    CalendarIcon: typeof import('./src/components/icons/CalendarIcon.vue')['default']
    CheckInQueuePanel: typeof import('./src/components/dashboard/CheckInQueuePanel.vue')['default']
    ClipboardIcon: typeof import('./src/components/icons/ClipboardIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    DateSelectionSection: typeof import('./src/components/booking/guest-assignment/DateSelectionSection.vue')['default']
    GuestAssignmentRow: typeof import('./src/components/booking/guest-assignment/GuestAssignmentRow.vue')['default']
    GuestAssignmentSection: typeof import('./src/components/booking/guest-assignment/GuestAssignmentSection.vue')['default']
    GuestCard: typeof import('./src/components/bookings/GuestCard.vue')['default']
    GuestDetails: typeof import('./src/components/bookings/steps/GuestDetails.vue')['default']
    GuestQuickCreate: typeof import('./src/components/booking/guest-assignment/GuestQuickCreate.vue')['default']
    GuestSelector: typeof import('./src/components/booking/guest-assignment/GuestSelector.vue')['default']
    ListIcon: typeof import('./src/components/icons/ListIcon.vue')['default']
    ListView: typeof import('./src/components/bookings/ListView.vue')['default']
    LiveTimelineBoard: typeof import('./src/components/dashboard/LiveTimelineBoard.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MpesaIcon: typeof import('./src/components/icons/MpesaIcon.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    NewGuestModal: typeof import('./src/components/bookings/NewGuestModal.vue')['default']
    OperationalAlertsPanel: typeof import('./src/components/dashboard/OperationalAlertsPanel.vue')['default']
    OperationalSummaryCards: typeof import('./src/components/dashboard/OperationalSummaryCards.vue')['default']
    PaypalIcon: typeof import('./src/components/icons/PaypalIcon.vue')['default']
    PlusIcon: typeof import('./src/components/icons/PlusIcon.vue')['default']
    PricingPackageDialog: typeof import('./src/components/services/PricingPackageDialog.vue')['default']
    ProviderAvailabilityStrip: typeof import('./src/components/dashboard/ProviderAvailabilityStrip.vue')['default']
    ResourceTimeline: typeof import('./src/components/dashboard/ResourceTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/Search.vue')['default']
    ServiceAssignmentCard: typeof import('./src/components/booking/guest-assignment/ServiceAssignmentCard.vue')['default']
    ServiceSelection: typeof import('./src/components/bookings/steps/ServiceSelection.vue')['default']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/common/SidebarItem.vue')['default']
    SlotCard: typeof import('./src/components/booking/guest-assignment/SlotCard.vue')['default']
    SlotSelection: typeof import('./src/components/bookings/steps/SlotSelection.vue')['default']
    SlotSelectionSection: typeof import('./src/components/booking/guest-assignment/SlotSelectionSection.vue')['default']
    TagIcon: typeof import('./src/components/icons/TagIcon.vue')['default']
    TimeSlotSkeleton: typeof import('./src/components/bookings/TimeSlotSkeleton.vue')['default']
    Topbar: typeof import('./src/components/common/Topbar.vue')['default']
  }
}
