/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarIcon: typeof import('./src/components/icons/CalendarIcon.vue')['default']
    ClipboardIcon: typeof import('./src/components/icons/ClipboardIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    ListIcon: typeof import('./src/components/icons/ListIcon.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MpesaIcon: typeof import('./src/components/icons/MpesaIcon.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    PaypalIcon: typeof import('./src/components/icons/PaypalIcon.vue')['default']
    PlusIcon: typeof import('./src/components/icons/PlusIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagIcon: typeof import('./src/components/icons/TagIcon.vue')['default']
  }
}
