/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCard: typeof import('./src/components/booking/AppointmentCard.vue')['default']
    BookingDialog: typeof import('./src/components/booking/BookingDialog.vue')['default']
    ChooseTime: typeof import('./src/components/booking/steps/ChooseTime.vue')['default']
    CustomerDetails: typeof import('./src/components/booking/steps/CustomerDetails.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    PaymentAndConfirmation: typeof import('./src/components/booking/steps/PaymentAndConfirmation.vue')['default']
    ProviderCard: typeof import('./src/components/providers/ProviderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/services/ServiceCard.vue')['default']
    ServiceTag: typeof import('./src/components/common/ServiceTag.vue')['default']
  }
}
