/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCard: typeof import('./src/components/booking/AppointmentCard.vue')['default']
    AppointmentCardSkeleton: typeof import('./src/components/booking/AppointmentCardSkeleton.vue')['default']
    BookingDialog: typeof import('./src/components/booking/BookingDialog.vue')['default']
    CategoryFilter: typeof import('./src/components/common/CategoryFilter.vue')['default']
    ChooseTime: typeof import('./src/components/booking/steps/ChooseTime.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    CustomerDetails: typeof import('./src/components/booking/steps/CustomerDetails.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MpesaIcon: typeof import('./src/components/icons/MpesaIcon.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PaymentAndConfirmation: typeof import('./src/components/booking/steps/PaymentAndConfirmation.vue')['default']
    PaymentGatewayList: typeof import('./src/components/booking/PaymentGatewayList.vue')['default']
    PaypalIcon: typeof import('./src/components/icons/PaypalIcon.vue')['default']
    ProviderCard: typeof import('./src/components/providers/ProviderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/services/ServiceCard.vue')['default']
    ServiceCardSkeleton: typeof import('./src/components/services/ServiceCardSkeleton.vue')['default']
    ServiceTag: typeof import('./src/components/common/ServiceTag.vue')['default']
    TimeSlotSkeleton: typeof import('./src/components/booking/TimeSlotSkeleton.vue')['default']
  }
}
