/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCard: typeof import('./src/components/AppointmentCard.vue')['default']
    BookingDialog: typeof import('./src/components/BookingDialog.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProviderCard: typeof import('./src/components/ProviderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/ServiceCard.vue')['default']
    ServiceTag: typeof import('./src/components/ServiceTag.vue')['default']
  }
}
