/** @type {import('tailwindcss').Config} */

import tailwindConfig from "frappe-ui/tailwind";

const themeColor = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

export default {
	presets: [tailwindConfig],
	content: [
		"./index.html",
		"./src/**/*.{vue,js,ts,jsx,tsx}",
		"./node_modules/frappe-ui/src/components/**/*.{vue,js,ts,jsx,tsx}",
		"../node_modules/frappe-ui/src/components/**/*.{vue,js,ts,jsx,tsx}",
	],
	theme: {
		extend: {
			colors: {
				"primary-fixed-dim": themeColor("primary-fixed-dim"),
				"surface-container-highest": themeColor("surface-container-highest"),
				"on-surface": themeColor("on-surface"),
				"on-primary-fixed-variant": themeColor("on-primary-fixed-variant"),
				"surface-container-lowest": themeColor("surface-container-lowest"),
				"on-secondary-container": themeColor("on-secondary-container"),
				"outline-variant": themeColor("outline-variant"),
				"on-error-container": "#93000a",
				"on-surface-variant": themeColor("on-surface-variant"),
				"on-background": themeColor("on-background"),
				tertiary: themeColor("tertiary"),
				"surface-container-high": themeColor("surface-container-high"),
				"tertiary-container": themeColor("tertiary-container"),
				"surface-tint": themeColor("surface-tint"),
				"on-tertiary-fixed-variant": themeColor("on-tertiary-fixed-variant"),
				"on-tertiary-fixed": themeColor("on-tertiary-fixed"),
				"on-primary": themeColor("on-primary"),
				"inverse-surface": themeColor("inverse-surface"),
				background: themeColor("background"),
				"background-light": themeColor("background-light"),
				"background-dark": themeColor("background-dark"),
				"on-tertiary": themeColor("on-tertiary"),
				"tertiary-fixed": themeColor("tertiary-fixed"),
				"tertiary-fixed-dim": themeColor("tertiary-fixed-dim"),
				"surface-bright": themeColor("surface-bright"),
				"secondary-fixed-dim": themeColor("secondary-fixed-dim"),
				secondary: themeColor("secondary"),
				"secondary-dark": themeColor("secondary-dark"),
				"secondary-ink": themeColor("secondary-ink"),
				primary: themeColor("primary"),
				"primary-dark": themeColor("primary-dark"),
				error: "#ba1a1a",
				"on-secondary": themeColor("on-secondary"),
				"primary-container": themeColor("primary-container"),
				"on-primary-container": themeColor("on-primary-container"),
				"on-primary-fixed": themeColor("on-primary-fixed"),
				"on-secondary-fixed": themeColor("on-secondary-fixed"),
				"surface-container": themeColor("surface-container"),
				"on-error": "#ffffff",
				"on-tertiary-container": themeColor("on-tertiary-container"),
				"inverse-on-surface": themeColor("inverse-on-surface"),
				"surface-container-low": themeColor("surface-container-low"),
				"inverse-primary": themeColor("inverse-primary"),
				"surface-variant": themeColor("surface-variant"),
				"secondary-fixed": themeColor("secondary-fixed"),
				"surface-dim": themeColor("surface-dim"),
				"surface-dark": themeColor("surface-dark"),
				"surface-light": themeColor("surface-light"),
				"primary-fixed": themeColor("primary-fixed"),
				"error-container": "#ffdad6",
				"on-secondary-fixed-variant": themeColor("on-secondary-fixed-variant"),
				"secondary-container": themeColor("secondary-container"),
				surface: themeColor("surface"),
				outline: themeColor("outline"),
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				"container-padding": "24px",
				gutter: "16px",
				"stack-sm": "12px",
				base: "8px",
				"section-gap": "48px",
				"stack-md": "24px",
			},
			fontFamily: {
				"label-md": ["Inter"],
				"headline-lg-mobile": ["Outfit"],
				"headline-lg": ["Outfit"],
				"body-md": ["Inter"],
				"label-sm": ["Inter"],
				"headline-md": ["Outfit"],
				"body-lg": ["Inter"],
				"headline-sm": ["Outfit"],
			},
			fontSize: {
				"label-md": [
					"14px",
					{ lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
				],
				"headline-lg-mobile": [
					"32px",
					{ lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" },
				],
				"headline-lg": [
					"40px",
					{ lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" },
				],
				"body-md": [
					"16px",
					{ lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" },
				],
				"label-sm": [
					"12px",
					{ lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" },
				],
				"headline-md": [
					"28px",
					{ lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" },
				],
				"body-lg": [
					"18px",
					{ lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" },
				],
				"headline-sm": [
					"20px",
					{ lineHeight: "28px", letterSpacing: "0em", fontWeight: "500" },
				],
			},
		},
	},
	plugins: [],
};
