/** @type {import('tailwindcss').Config} */

import tailwindConfig from "frappe-ui/tailwind";

export default {
	presets: [tailwindConfig],
	content: [
		"./index.html",
		"./src/**/*.{vue,js,ts,jsx,tsx}",
		"./node_modules/frappe-ui/src/components/**/*.{vue,js,ts,jsx,tsx}",
		"../node_modules/frappe-ui/src/components/**/*.{vue,js,ts,jsx,tsx}",
	],
	theme: {
		extend: {
			colors: {
				"primary-fixed-dim": "#71d7cd",
				"surface-container-highest": "#dde4e6",
				"on-surface": "#161d1f",
				"on-primary-fixed-variant": "#00504a",
				"surface-container-lowest": "#ffffff",
				"on-secondary-container": "#2e7238",
				"outline-variant": "#bdc9c6",
				"on-error-container": "#93000a",
				"on-surface-variant": "#3d4947",
				"on-background": "#161d1f",
				tertiary: "#9f4122",
				"surface-container-high": "#e2e9ec",
				"tertiary-container": "#f98661",
				"surface-tint": "#006a63",
				"on-tertiary-fixed-variant": "#7f2a0d",
				"on-tertiary-fixed": "#3a0b00",
				"on-primary": "#ffffff",
				"inverse-surface": "#2b3234",
				background: "#f4fafd",
				"on-tertiary": "#ffffff",
				"tertiary-fixed": "#ffdbd0",
				"surface-bright": "#f4fafd",
				"secondary-fixed-dim": "#90d792",
				secondary: "#286b33",
				primary: "#006a63",
				error: "#ba1a1a",
				"on-secondary": "#ffffff",
				"primary-container": "#4db6ac",
				"on-primary-fixed": "#00201d",
				"on-secondary-fixed": "#002107",
				"surface-container": "#e8eff1",
				"on-error": "#ffffff",
				"on-tertiary-container": "#701f03",
				"tertiary-fixed-dim": "#ffb59e",
				"on-primary-container": "#00433f",
				"inverse-on-surface": "#ebf2f4",
				"surface-container-low": "#eef5f7",
				"inverse-primary": "#71d7cd",
				"surface-variant": "#dde4e6",
				"secondary-fixed": "#abf4ac",
				"surface-dim": "#d4dbdd",
				"primary-fixed": "#8ef4e9",
				"error-container": "#ffdad6",
				"on-secondary-fixed-variant": "#07521d",
				"secondary-container": "#abf4ac",
				surface: "#f4fafd",
				outline: "#6d7a77",
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				"container-padding": "24px",
				gutter: "16px",
				"stack-sm": "12px",
				base: "8px",
				"section-gap": "48px",
				"stack-md": "24px",
			},
			fontFamily: {
				"label-md": ["Inter"],
				"headline-lg-mobile": ["Outfit"],
				"headline-lg": ["Outfit"],
				"body-md": ["Inter"],
				"label-sm": ["Inter"],
				"headline-md": ["Outfit"],
				"body-lg": ["Inter"],
				"headline-sm": ["Outfit"],
			},
			fontSize: {
				"label-md": [
					"14px",
					{ lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
				],
				"headline-lg-mobile": [
					"32px",
					{ lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" },
				],
				"headline-lg": [
					"40px",
					{ lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" },
				],
				"body-md": [
					"16px",
					{ lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" },
				],
				"label-sm": [
					"12px",
					{ lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" },
				],
				"headline-md": [
					"28px",
					{ lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" },
				],
				"body-lg": [
					"18px",
					{ lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" },
				],
				"headline-sm": [
					"20px",
					{ lineHeight: "28px", letterSpacing: "0em", fontWeight: "500" },
				],
			},
		},
	},
	plugins: [],
};
