export function createEmptyAppointmentDetails() {
	return {
		name: "",
		appointmentId: "",
		bookingId: "",
		status: "Open",
		paymentStatus: "Unpaid",
		customer: "",
		customerName: "",
		fullName: "",
		email: "",
		mobileNo: "",
		currency: "KES",
		appointmentType: "",
		appointmentDate: "",
		startTime: "",
		endTime: "",
		actualStartTime: "",
		actualEndTime: "",
		duration: 0,
		serviceUnit: "",
		provider: "",
		serviceProviderName: "",
		appointmentPrice: "",
		totalAmount: 0,
		grandTotal: 0,
		outstandingAmount: 0,
		details: "",
		notes: "",
		source: "",
		selectedSlotIds: [],
		allAvailableProviders: [],
		modified: "",
		creation: "",
	};
}
